### ISSUE TITLE
globby 8.0.1 dependency is broken

### ISSUE THREAD

**Issue by rvillane** [the-simian/es6-plato#76]
issue is documented here https://github.com/sindresorhus/globby/issues/98  
It causes:

path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at getPath (/Users/crmar/GitHub_Storage/direct-order-sales-updater/node_modules/dir-glob/index.js:6:41)
    at globs.concat.map.x (/Users/crmar/GitHub_Storage/direct-order-sales-updater/node_modules/dir-glob/index.js:47:59)
    at Array.map (<anonymous>)
    at module.exports.sync (/Users/crmar/GitHub_Storage/direct-order-sales-updater/node_modules/dir-glob/index.js:47:33)
    at globDirs (/Users/crmar/GitHub_Storage/direct-order-sales-updater/node_modules/globby/index.js:58:9)
    at getPattern (/Users/crmar/GitHub_Storage/direct-order-sales-updater/node_modules/globby/index.js:61:64)
    at globTasks.reduce (/Users/crmar/GitHub_Storage/direct-order-sales-updater/node_modules/globby/index.js:107:19)
    at Array.reduce (<anonymous>)

to fix it es6-plato needs to point to globby 8.0.2

**Comment by sumeetkakkar** [comment]
Here's another error because of broken globby 8.0.1. dependency. This was fixed under 
https://github.com/sindresorhus/globby/pull/99.

/Users/dev/git/node_modules/dir-glob/index.js:62
    throw new TypeError(`Expected \`cwd\` to be of type \`string\` but received type \`${typeof opts.cwd}\``);
    ^

TypeError: Expected `cwd` to be of type `string` but received type `undefined`
    at module.exports.sync (/Users/dev/git/node_modules/dir-glob/index.js:62:9)
    at globDirs (/Users/dev/git/node_modules/globby/index.js:60:9)
    at getPattern (/Users/dev/git/node_modules/globby/index.js:63:64)
    at globTasks.reduce (/Users/dev/git/node_modules/globby/index.js:109:19)
    at Array.reduce (<anonymous>)
    at Function.module.exports.sync (/Users/dev/git/node_modules/globby/index.js:108:26)
    at patternToFile (/Users/dev/git/node_modules/es6-plato/lib/plato.js:56:16)
    at arrayMap (/Users/dev/git/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/dev/git/node_modules/lodash/lodash.js:9554:14)
    at interceptor (/Users/dev/git/node_modules/lodash/lodash.js:16991:35)

**Comment by the-simian** [comment]
thanks @rvillane and @sumeetkakkar seems like a super simple fix

**Comment by niktekusho** [comment]
I just encountered this myself.
I've just tried the @njhoffman fork, and it completes the analysis without errors.
If @njhoffman does not mind, I would be happy to open a PR about this.

**Comment by njhoffman** [comment]
Of course, let me know if there's anything else I can to do help.
